after_script:
  - NODE_ENV=test
  - istanbul cover ./node_modules/mocha/bin/_mocha
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
language: node_js
os:
  - osx
  - linux
node_js:
  - stable
sudo: false
